### ISSUE TITLE
Parse desktop files with Terminal=true

### ISSUE THREAD

**Issue by chiku** [chiku/mjwm#47]

**Comment by sighook** [comment]
There is the "quick and dirty" patch to parse `Terminal=true` entry.

This is of course a very dirty patch with some hard-coded things and a good one should add a new feature like specifying a terminal from the command line, take into account escape symbols, and undoubtedly this should be reflected in the man page. Just... I'll just leave this for those who need a quick solution to their problem.

```patch
diff --git a/src/xdg/desktop_entry.cc b/src/xdg/desktop_entry.cc
index 65c7bbc..cc0f18f 100644
--- a/src/xdg/desktop_entry.cc
+++ b/src/xdg/desktop_entry.cc
@@ -34,7 +34,12 @@ void DesktopEntry::parse(const std::vector<std::string> &lines)
     xdg_entry.parse();
     name_ = xdg_entry.under("Desktop Entry", "Name");
     icon_ = xdg_entry.under("Desktop Entry", "Icon");
-    executable_ = xdg_entry.under("Desktop Entry", "Exec");
+    std::string terminal_ = xdg_entry.under("Desktop Entry", "Terminal");
+    std::string executable_raw = xdg_entry.under("Desktop Entry", "Exec");
+    if (terminal_ == "1" || terminal_ == "true")
+        executable_ = "xterm -class \"" + name_ + "\" -e " + executable_raw;
+    else
+        executable_ = executable_raw;
     categories_ = StringX(xdg_entry.under("Desktop Entry", "Categories")).split(";");
     comment_ = xdg_entry.under("Desktop Entry", "Comment");
     std::string display_raw = xdg_entry.under("Desktop Entry", "NoDisplay");
```

God bless you, @chiku, and let's cross our fingers that #47 feature will appear in the new release :smile:.  Thanks for `mjwm`, btw, it's really a good tool.

**Comment by chiku** [comment]
`mjwm` reads `$TERM` environment variable to find the terminal to use. Currently `mjwm` supports `alacritty`, `sakura` & `xterm`. If a terminal is not recognized, `mjwm` assumes the terminal to be `xterm`.

You could override the terminal to use by explicitly running `mjwm` with the supported terminal of your choice.

```script
TERM=sakura mjwm
```

**Comment by sighook** [comment]
Thank you very much.
